### ISSUE TITLE
Creating octopusdeploy_kubernetes_cluster_deployment_target result in unhandled exception

### ISSUE THREAD

**Issue by nmlc** [OctopusDeploy/terraform-provider-octopusdeploy#118]
**Describe the bug**
Couldn't create `octopusdeploy_kubernetes_cluster_deployment_target` resource, `terraform apply` crushed with an exception.

**Steps to reproduce**
```
resource "octopusdeploy_kubernetes_cluster_deployment_target" "main" {
  name        = "test"
  cluster_url = "<url>"
  roles = [
    "test"
  ]

  authentication {
    account_id = "<valid-account-id>"
  }

}
```

**Expected behavior**
Deployment target is created

**Logs and other supporting information**
```
octopusdeploy_kubernetes_cluster_deployment_target.main: Creating...

Error: rpc error: code = Unavailable desc = transport is closing



Error: rpc error: code = Unavailable desc = transport is closing


panic: runtime error: index out of range [0] with length 0
2021-01-11T15:15:45.113+0500 [DEBUG] plugin.terraform-provider-octopusdeploy:
2021-01-11T15:15:45.113+0500 [DEBUG] plugin.terraform-provider-octopusdeploy: goroutine 28 [running]:
2021-01-11T15:15:45.113+0500 [DEBUG] plugin.terraform-provider-octopusdeploy: github.com/OctopusDeploy/terraform-provider-octopusdeploy/octopusdeploy.expandEndpoint(0x189a8a0, 0xc00048a240, 0x8, 0x189a8a0)
2021-01-11T15:15:45.113+0500 [DEBUG] plugin.terraform-provider-octopusdeploy:   /Users/Maltsev/mb/terraform-provider-octopusdeploy/octopusdeploy/schema_endpoint.go:11 +0xe0c
2021-01-11T15:15:45.113+0500 [DEBUG] plugin.terraform-provider-octopusdeploy: github.com/OctopusDeploy/terraform-provider-octopusdeploy/octopusdeploy.expandDeploymentTarget(0xc00037da00, 0x1a0437e)
2021-01-11T15:15:45.113+0500 [DEBUG] plugin.terraform-provider-octopusdeploy:   /Users/Maltsev/mb/terraform-provider-octopusdeploy/octopusdeploy/schema_deployment_target.go:13 +0xc7
2021-01-11T15:15:45.113+0500 [DEBUG] plugin.terraform-provider-octopusdeploy: github.com/OctopusDeploy/terraform-provider-octopusdeploy/octopusdeploy.expandKubernetesClusterDeploymentTarget(0xc00037da00, 0xc0005cf600)
2021-01-11T15:15:45.113+0500 [DEBUG] plugin.terraform-provider-octopusdeploy:   /Users/Maltsev/mb/terraform-provider-octopusdeploy/octopusdeploy/schema_kubernetes_cluster_deployment_target.go:57 +0x8f1
2021-01-11T15:15:45.113+0500 [DEBUG] plugin.terraform-provider-octopusdeploy: github.com/OctopusDeploy/terraform-provider-octopusdeploy/octopusdeploy.resourceKubernetesClusterDeploymentTargetCreate(0x1b548a0, 0xc000058660, 0xc00037da00, 0x187d2e0, 0xc0000d0a00, 0xc00023a990, 0x14f7e2a, 0xc000875000)
2021-01-11T15:15:45.113+0500 [DEBUG] plugin.terraform-provider-octopusdeploy:   /Users/Maltsev/mb/terraform-provider-octopusdeploy/octopusdeploy/resource_kubernetes_cluster_deployment_target.go:25 +0x43
2021-01-11T15:15:45.113+0500 [DEBUG] plugin.terraform-provider-octopusdeploy: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc0002829a0, 0x1b54820, 0xc0003af1c0, 0xc00037da00, 0x187d2e0, 0xc0000d0a00, 0x0, 0x0, 0x0)
2021-01-11T15:15:45.113+0500 [DEBUG] plugin.terraform-provider-octopusdeploy:   /Users/Maltsev/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.3.0/helper/schema/resource.go:275 +0x1ec
2021-01-11T15:15:45.113+0500 [DEBUG] plugin.terraform-provider-octopusdeploy: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0002829a0, 0x1b54820, 0xc0003af1c0, 0xc0000eb3b0, 0xc000875000, 0x187d2e0, 0xc0000d0a00, 0x0, 0x0, 0x0, ...)
2021-01-11T15:15:45.113+0500 [DEBUG] plugin.terraform-provider-octopusdeploy:   /Users/Maltsev/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.3.0/helper/schema/resource.go:386 +0x681
2021-01-11T15:15:45.113+0500 [DEBUG] plugin.terraform-provider-octopusdeploy: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc0003b8da0, 0x1b54820, 0xc0003af1c0, 0xc000122eb0, 0xc0003af1c0, 0xc000415d00, 0x1b61940)
2021-01-11T15:15:45.113+0500 [DEBUG] plugin.terraform-provider-octopusdeploy:   /Users/Maltsev/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.3.0/helper/schema/grpc_provider.go:951 +0x8b2
2021-01-11T15:15:45.113+0500 [DEBUG] plugin.terraform-provider-octopusdeploy: github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ApplyResourceChange(0xc00048a6c0, 0x1b54820, 0xc0003af1c0, 0xc0000eb260, 0xc00048a6c0, 0xc000928630, 0xc000897ba0)
2021-01-11T15:15:45.113+0500 [DEBUG] plugin.terraform-provider-octopusdeploy:   /Users/Maltsev/go/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.2.0/tfprotov5/server/server.go:331 +0xac
2021-01-11T15:15:45.113+0500 [DEBUG] plugin.terraform-provider-octopusdeploy: github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x19b2740, 0xc00048a6c0, 0x1b548e0, 0xc000928630, 0xc000415da0, 0x0, 0x1b548e0, 0xc000928630, 0xc0007a2680, 0x526)
2021-01-11T15:15:45.113+0500 [DEBUG] plugin.terraform-provider-octopusdeploy:   /Users/Maltsev/go/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.2.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:380 +0x217
2021-01-11T15:15:45.113+0500 [DEBUG] plugin.terraform-provider-octopusdeploy: google.golang.org/grpc.(*Server).processUnaryRPC(0xc000400540, 0x1b5edc0, 0xc000603080, 0xc0005dc500, 0xc00032f2f0, 0x2174e20, 0x0, 0x0, 0x0)
2021-01-11T15:15:45.113+0500 [DEBUG] plugin.terraform-provider-octopusdeploy:   /Users/Maltsev/go/pkg/mod/google.golang.org/grpc@v1.34.0/server.go:1210 +0x50a
2021-01-11T15:15:45.113+0500 [DEBUG] plugin.terraform-provider-octopusdeploy: google.golang.org/grpc.(*Server).handleStream(0xc000400540, 0x1b5edc0, 0xc000603080, 0xc0005dc500, 0x0)
2021-01-11T15:15:45.113+0500 [DEBUG] plugin.terraform-provider-octopusdeploy:   /Users/Maltsev/go/pkg/mod/google.golang.org/grpc@v1.34.0/server.go:1533 +0xcfd
2021-01-11T15:15:45.113+0500 [DEBUG] plugin.terraform-provider-octopusdeploy: google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc000218920, 0xc000400540, 0x1b5edc0, 0xc000603080, 0xc0005dc500)
2021-01-11T15:15:45.113+0500 [DEBUG] plugin.terraform-provider-octopusdeploy:   /Users/Maltsev/go/pkg/mod/google.golang.org/grpc@v1.34.0/server.go:871 +0xa1
2021-01-11T15:15:45.113+0500 [DEBUG] plugin.terraform-provider-octopusdeploy: created by google.golang.org/grpc.(*Server).serveStreams.func1
2021-01-11T15:15:45.113+0500 [DEBUG] plugin.terraform-provider-octopusdeploy:   /Users/Maltsev/go/pkg/mod/google.golang.org/grpc@v1.34.0/server.go:869 +0x204
2021-01-11T15:15:45.116+0500 [WARN]  plugin.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
2021/01/11 15:15:45 [DEBUG] octopusdeploy_token_account.cluster_account: apply errored, but we're indicating that via the Error pointer rather than returning it: rpc error: code = Unavailable desc = transport is closing
2021/01/11 15:15:45 [DEBUG] octopusdeploy_kubernetes_cluster_deployment_target.main: apply errored, but we're indicating that via the Error pointer rather than returning it: rpc error: code = Unavailable desc = transport is closing
2021/01/11 15:15:45 [TRACE] eval: *terraform.EvalMaybeTainted
2021/01/11 15:15:45 [TRACE] eval: *terraform.EvalWriteState
2021/01/11 15:15:45 [TRACE] EvalMaybeTainted: octopusdeploy_kubernetes_cluster_deployment_target.main encountered an error during creation, so it is now marked as tainted
2021/01/11 15:15:45 [TRACE] eval: *terraform.EvalWriteState
2021/01/11 15:15:45 [TRACE] EvalWriteState: removing state object for octopusdeploy_kubernetes_cluster_deployment_target.main
2021/01/11 15:15:45 [TRACE] eval: *terraform.EvalApplyProvisioners
2021/01/11 15:15:45 [TRACE] EvalWriteState: writing current state object for octopusdeploy_token_account.cluster_account
2021/01/11 15:15:45 [TRACE] EvalApplyProvisioners: octopusdeploy_kubernetes_cluster_deployment_target.main has no state, so skipping provisioners
2021/01/11 15:15:45 [TRACE] eval: *terraform.EvalMaybeTainted
2021/01/11 15:15:45 [TRACE] EvalMaybeTainted: octopusdeploy_kubernetes_cluster_deployment_target.main encountered an error during creation, so it is now marked as tainted
2021/01/11 15:15:45 [TRACE] eval: *terraform.EvalWriteState
2021/01/11 15:15:45 [TRACE] EvalWriteState: removing state object for octopusdeploy_kubernetes_cluster_deployment_target.main
2021/01/11 15:15:45 [TRACE] eval: *terraform.EvalIf
2021/01/11 15:15:45 [TRACE] eval: *terraform.EvalIf
2021/01/11 15:15:45 [TRACE] eval: *terraform.EvalWriteDiff
2021/01/11 15:15:45 [TRACE] eval: *terraform.EvalApplyPost
2021/01/11 15:15:45 [ERROR] eval: *terraform.EvalApplyPost, err: rpc error: code = Unavailable desc = transport is closing
2021/01/11 15:15:45 [ERROR] eval: *terraform.EvalSequence, err: rpc error: code = Unavailable desc = transport is closing
2021/01/11 15:15:45 [TRACE] [walkApply] Exiting eval tree: octopusdeploy_kubernetes_cluster_deployment_target.main
2021/01/11 15:15:45 [TRACE] vertex "octopusdeploy_kubernetes_cluster_deployment_target.main": visit complete
2021-01-11T15:15:45.116+0500 [DEBUG] plugin: plugin process exited: path=.terraform/plugins/octopus.com/com/octopusdeploy/0.6.0/darwin_amd64/terraform-provider-octopusdeploy pid=43351 error="exit status 2"
2021/01/11 15:15:45 [TRACE] eval: *terraform.EvalApplyPost
2021/01/11 15:15:45 [ERROR] eval: *terraform.EvalApplyPost, err: rpc error: code = Unavailable desc = transport is closing
2021/01/11 15:15:45 [ERROR] eval: *terraform.EvalSequence, err: rpc error: code = Unavailable desc = transport is closing
2021/01/11 15:15:45 [ERROR] eval: *terraform.EvalOpFilter, err: rpc error: code = Unavailable desc = transport is closing
2021/01/11 15:15:45 [TRACE] [walkApply] Exiting eval tree: octopusdeploy_token_account.cluster_account (destroy)
2021/01/11 15:15:45 [TRACE] vertex "octopusdeploy_token_account.cluster_account (destroy)": visit complete
2021/01/11 15:15:45 [TRACE] dag/walk: upstream of "meta.count-boundary (EachMode fixup)" errored, so skipping
2021/01/11 15:15:45 [TRACE] dag/walk: upstream of "provider[\"octopus.com/com/octopusdeploy\"] (close)" errored, so skipping
2021/01/11 15:15:45 [TRACE] dag/walk: upstream of "root" errored, so skipping
2021/01/11 15:15:45 [TRACE] statemgr.Filesystem: not making a backup, because the new snapshot is identical to the old
2021/01/11 15:15:45 [TRACE] statemgr.Filesystem: no state changes since last snapshot
2021/01/11 15:15:45 [TRACE] statemgr.Filesystem: writing snapshot at terraform.tfstate
2021/01/11 15:15:45 [TRACE] statemgr.Filesystem: removing lock metadata file .terraform.tfstate.lock.info
2021/01/11 15:15:45 [TRACE] statemgr.Filesystem: unlocking terraform.tfstate using fcntl flock
2021-01-11T15:15:45.142+0500 [DEBUG] plugin: plugin exited



!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

SECURITY WARNING: the "crash.log" file that was created may contain
sensitive information that must be redacted before it is safe to share
on the issue tracker.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

**Environment and versions:**
OS: `OSX`
Octopus Server Version: `2020.4.11`
Terraform Version: `0.13.0`
Octopus Terraform Provider Version: `beta-candidate-01` branch

**Comment by nmlc** [comment]
@jbristowe can't reproduce on https://github.com/OctopusDeploy/terraform-provider-octopusdeploy/commit/d12681c218a64f836fb9b4be3e0123bd37d5a78c. Seems like a regression.

**Comment by jbristowe** [comment]
@nmlc Please get latest and try the fix I implemented. Thanks!

**Comment by nmlc** [comment]
@jbristowe Hmm, first apply does work. But when I change something, for example environments, I catch another crush:
```
panic: interface conversion: interface {} is *schema.Set, not []interface {}
2021-01-12T13:49:40.018+0500 [DEBUG] plugin.terraform-provider-octopusdeploy:
2021-01-12T13:49:40.018+0500 [DEBUG] plugin.terraform-provider-octopusdeploy: goroutine 83 [running]:
2021-01-12T13:49:40.018+0500 [DEBUG] plugin.terraform-provider-octopusdeploy: github.com/OctopusDeploy/terraform-provider-octopusdeploy/octopusdeploy.expandKubernetesAuthentication(0x19b87a0, 0xc0000fc9e0, 0x19fe43a, 0xe)
2021-01-12T13:49:40.018+0500 [DEBUG] plugin.terraform-provider-octopusdeploy:   /Users/Maltsev/mb/terraform-provider-octopusdeploy/octopusdeploy/schema_kubernetes_authentication.go:10 +0xb6d
2021-01-12T13:49:40.018+0500 [DEBUG] plugin.terraform-provider-octopusdeploy: github.com/OctopusDeploy/terraform-provider-octopusdeploy/octopusdeploy.expandKubernetesCluster(0xc00045cc90, 0xc00045cc90)
2021-01-12T13:49:40.018+0500 [DEBUG] plugin.terraform-provider-octopusdeploy:   /Users/Maltsev/mb/terraform-provider-octopusdeploy/octopusdeploy/schema_kubernetes_cluster.go:14 +0x18d
2021-01-12T13:49:40.018+0500 [DEBUG] plugin.terraform-provider-octopusdeploy: github.com/OctopusDeploy/terraform-provider-octopusdeploy/octopusdeploy.expandEndpoint(0x189a880, 0xc0000fd5a0, 0x8, 0x189a880)
2021-01-12T13:49:40.018+0500 [DEBUG] plugin.terraform-provider-octopusdeploy:   /Users/Maltsev/mb/terraform-provider-octopusdeploy/octopusdeploy/schema_endpoint.go:26 +0x3a7
2021-01-12T13:49:40.018+0500 [DEBUG] plugin.terraform-provider-octopusdeploy: github.com/OctopusDeploy/terraform-provider-octopusdeploy/octopusdeploy.expandDeploymentTarget(0xc0004bc900, 0x1a04354)
2021-01-12T13:49:40.018+0500 [DEBUG] plugin.terraform-provider-octopusdeploy:   /Users/Maltsev/mb/terraform-provider-octopusdeploy/octopusdeploy/schema_deployment_target.go:13 +0xc7
2021-01-12T13:49:40.018+0500 [DEBUG] plugin.terraform-provider-octopusdeploy: github.com/OctopusDeploy/terraform-provider-octopusdeploy/octopusdeploy.expandKubernetesClusterDeploymentTarget(0xc0004bc900, 0x39)
2021-01-12T13:49:40.018+0500 [DEBUG] plugin.terraform-provider-octopusdeploy:   /Users/Maltsev/mb/terraform-provider-octopusdeploy/octopusdeploy/schema_kubernetes_cluster_deployment_target.go:57 +0x8f1
2021-01-12T13:49:40.018+0500 [DEBUG] plugin.terraform-provider-octopusdeploy: github.com/OctopusDeploy/terraform-provider-octopusdeploy/octopusdeploy.resourceKubernetesClusterDeploymentTargetUpdate(0x1b54860, 0xc000480d80, 0xc0004bc900, 0x187d2c0, 0xc000140a00, 0xc000801580, 0x14f7e2a, 0xc0003ce480)
2021-01-12T13:49:40.018+0500 [DEBUG] plugin.terraform-provider-octopusdeploy:   /Users/Maltsev/mb/terraform-provider-octopusdeploy/octopusdeploy/resource_kubernetes_cluster_deployment_target.go:85 +0xf2
2021-01-12T13:49:40.018+0500 [DEBUG] plugin.terraform-provider-octopusdeploy: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).update(0xc000290f20, 0x1b547e0, 0xc0000a4780, 0xc0004bc900, 0x187d2c0, 0xc000140a00, 0x0, 0x0, 0x0)
2021-01-12T13:49:40.018+0500 [DEBUG] plugin.terraform-provider-octopusdeploy:   /Users/Maltsev/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.3.0/helper/schema/resource.go:299 +0x1ec
2021-01-12T13:49:40.018+0500 [DEBUG] plugin.terraform-provider-octopusdeploy: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc000290f20, 0x1b547e0, 0xc0000a4780, 0xc0001a0460, 0xc0003ce480, 0x187d2c0, 0xc000140a00, 0x0, 0x0, 0x0, ...)
2021-01-12T13:49:40.018+0500 [DEBUG] plugin.terraform-provider-octopusdeploy:   /Users/Maltsev/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.3.0/helper/schema/resource.go:394 +0x392
2021-01-12T13:49:40.018+0500 [DEBUG] plugin.terraform-provider-octopusdeploy: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc00062abc0, 0x1b547e0, 0xc0000a4780, 0xc0003a25a0, 0xc0000a4780, 0xc000058500, 0x1b61900)
2021-01-12T13:49:40.018+0500 [DEBUG] plugin.terraform-provider-octopusdeploy:   /Users/Maltsev/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.3.0/helper/schema/grpc_provider.go:951 +0x8b2
2021-01-12T13:49:40.018+0500 [DEBUG] plugin.terraform-provider-octopusdeploy: github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ApplyResourceChange(0xc00062b040, 0x1b547e0, 0xc0000a4780, 0xc0001a0000, 0xc00062b040, 0xc0005dc1b0, 0xc0007fcba0)
2021-01-12T13:49:40.019+0500 [DEBUG] plugin.terraform-provider-octopusdeploy:   /Users/Maltsev/go/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.2.0/tfprotov5/server/server.go:331 +0xac
2021-01-12T13:49:40.019+0500 [DEBUG] plugin.terraform-provider-octopusdeploy: github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x19b2720, 0xc00062b040, 0x1b548a0, 0xc0005dc1b0, 0xc000058540, 0x0, 0x1b548a0, 0xc0005dc1b0, 0xc0005e8600, 0x1199)
2021-01-12T13:49:40.019+0500 [DEBUG] plugin.terraform-provider-octopusdeploy:   /Users/Maltsev/go/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.2.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:380 +0x217
2021-01-12T13:49:40.019+0500 [DEBUG] plugin.terraform-provider-octopusdeploy: google.golang.org/grpc.(*Server).processUnaryRPC(0xc0004aa1c0, 0x1b5ed80, 0xc000602a80, 0xc0005e4000, 0xc0004833b0, 0x2174e20, 0x0, 0x0, 0x0)
2021-01-12T13:49:40.019+0500 [DEBUG] plugin.terraform-provider-octopusdeploy:   /Users/Maltsev/go/pkg/mod/google.golang.org/grpc@v1.34.0/server.go:1210 +0x50a
2021-01-12T13:49:40.019+0500 [DEBUG] plugin.terraform-provider-octopusdeploy: google.golang.org/grpc.(*Server).handleStream(0xc0004aa1c0, 0x1b5ed80, 0xc000602a80, 0xc0005e4000, 0x0)
2021-01-12T13:49:40.019+0500 [DEBUG] plugin.terraform-provider-octopusdeploy:   /Users/Maltsev/go/pkg/mod/google.golang.org/grpc@v1.34.0/server.go:1533 +0xcfd
2021-01-12T13:49:40.019+0500 [DEBUG] plugin.terraform-provider-octopusdeploy: google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc000134520, 0xc0004aa1c0, 0x1b5ed80, 0xc000602a80, 0xc0005e4000)
2021-01-12T13:49:40.019+0500 [DEBUG] plugin.terraform-provider-octopusdeploy:   /Users/Maltsev/go/pkg/mod/google.golang.org/grpc@v1.34.0/server.go:871 +0xa1
2021-01-12T13:49:40.019+0500 [DEBUG] plugin.terraform-provider-octopusdeploy: created by google.golang.org/grpc.(*Server).serveStreams.func1
2021-01-12T13:49:40.019+0500 [DEBUG] plugin.terraform-provider-octopusdeploy:   /Users/Maltsev/go/pkg/mod/google.golang.org/grpc@v1.34.0/server.go:869 +0x204
2021-01-12T13:49:40.021+0500 [WARN]  plugin.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
2021-01-12T13:49:40.021+0500 [DEBUG] plugin: plugin process exited: path=.terraform/plugins/octopus.com/com/octopusdeploy/0.6.0/darwin_amd64/terraform-provider-octopusdeploy pid=75869 error="exit status 2"
2021/01/12 13:49:40 [DEBUG] octopusdeploy_kubernetes_cluster_deployment_target.main: apply errored, but we're indicating that via the Error pointer rather than returning it: rpc error: code = Unavailable desc = transport is closing
2021/01/12 13:49:40 [TRACE] eval: *terraform.EvalMaybeTainted
2021/01/12 13:49:40 [TRACE] eval: *terraform.EvalWriteState
2021/01/12 13:49:40 [TRACE] EvalWriteState: recording 2 dependencies for octopusdeploy_kubernetes_cluster_deployment_target.main
2021/01/12 13:49:40 [TRACE] EvalWriteState: writing current state object for octopusdeploy_kubernetes_cluster_deployment_target.main
2021/01/12 13:49:40 [TRACE] eval: *terraform.EvalApplyProvisioners
2021/01/12 13:49:40 [TRACE] EvalApplyProvisioners: octopusdeploy_kubernetes_cluster_deployment_target.main is not freshly-created, so no provisioning is required
2021/01/12 13:49:40 [TRACE] eval: *terraform.EvalMaybeTainted
2021/01/12 13:49:40 [TRACE] eval: *terraform.EvalWriteState
2021/01/12 13:49:40 [TRACE] EvalWriteState: recording 2 dependencies for octopusdeploy_kubernetes_cluster_deployment_target.main
2021/01/12 13:49:40 [TRACE] EvalWriteState: writing current state object for octopusdeploy_kubernetes_cluster_deployment_target.main
2021/01/12 13:49:40 [TRACE] eval: *terraform.EvalIf
2021/01/12 13:49:40 [TRACE] eval: *terraform.EvalIf
2021/01/12 13:49:40 [TRACE] eval: *terraform.EvalWriteDiff
2021/01/12 13:49:40 [TRACE] eval: *terraform.EvalApplyPost
2021/01/12 13:49:40 [ERROR] eval: *terraform.EvalApplyPost, err: rpc error: code = Unavailable desc = transport is closing
2021/01/12 13:49:40 [ERROR] eval: *terraform.EvalSequence, err: rpc error: code = Unavailable desc = transport is closing
2021/01/12 13:49:40 [TRACE] [walkApply] Exiting eval tree: octopusdeploy_kubernetes_cluster_deployment_target.main
2021/01/12 13:49:40 [TRACE] vertex "octopusdeploy_kubernetes_cluster_deployment_target.main": visit complete
2021/01/12 13:49:40 [TRACE] dag/walk: upstream of "meta.count-boundary (EachMode fixup)" errored, so skipping
2021/01/12 13:49:40 [TRACE] dag/walk: upstream of "provider[\"octopus.com/com/octopusdeploy\"] (close)" errored, so skipping
2021/01/12 13:49:40 [TRACE] dag/walk: upstream of "root" errored, so skipping
2021/01/12 13:49:40 [TRACE] statemgr.Filesystem: have already backed up original terraform.tfstate to terraform.tfstate.backup on a previous write
2021/01/12 13:49:40 [TRACE] statemgr.Filesystem: state has changed since last snapshot, so incrementing serial to 8
2021/01/12 13:49:40 [TRACE] statemgr.Filesystem: writing snapshot at terraform.tfstate
2021/01/12 13:49:40 [TRACE] statemgr.Filesystem: removing lock metadata file .terraform.tfstate.lock.info
2021/01/12 13:49:40 [TRACE] statemgr.Filesystem: unlocking terraform.tfstate using fcntl flock
2021-01-12T13:49:40.047+0500 [DEBUG] plugin: plugin exited
```

**Comment by jbristowe** [comment]
Possible fix. Please try with latest and let me know how it goes.

**Comment by nmlc** [comment]
Yep, looks like it does work now. Thank you for a quick fix 👍

**Comment by sd2302** [comment]
Hello @jbristowe @nmlc 
We are using OD 2020.2.2, Is there a Getting Started Guide to deploy Octopus Targets  using TF 0.14.4 eg OD K8 Cluster Target pas this issue ?

**Comment by sd2302** [comment]
Is this my best bet ?

https://github.com/OctopusDeploy/go-octopusdeploy/tree/master/examples

**Comment by jbristowe** [comment]
Hey @sd2302! 👋 There isn't a "getting started guide" at this time. It's a good idea!

**Comment by joelhays** [comment]
I'm getting this same error on 0.7.3 plugin as well as this one (seems random which one I'll get) -- using the same basic config.

Error: Octopus API error: Value cannot be null.
Parameter name: source []
